name: Build Test Coverage

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  build-and-test-dotnet:
    name: Build Test Coverage
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest

    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup .NET 7.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: NuGet Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.csproj') }}

      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Build .NET Project
        run: |
          dotnet build --no-restore /p:ContinuousIntegrationBuild=true --configuration Release
          
      - name: Run unit tests
        run: |
          dotnet test SaloAPI.UnitTests/MangoAPI.UnitTests.csproj --configuration Release --no-build
        env:
          CollectCoverage: true
          CoverletOutputFormat: lcov
          ThresholdStat: total
          ThresholdType: Line
          CoverletOutput: TestResults/

      - name: Run Integration Tests
        run: |
          dotnet test SaloAPI.IntegrationTests/SaloAPI.IntegrationTests.csproj --configuration Release --no-build
        env:
          CollectCoverage: true
          CoverletOutputFormat: lcov
          ThresholdStat: total
          ThresholdType: Line
          CoverletOutput: TestResults/
      # dotnet test SaloAPI.IntegrationTests/SaloAPI.IntegrationTests.csproj -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=lcov

      - name: Publish .NET Project
        run: |
          dotnet publish "SaloAPI.Presentation/SaloAPI.Presentation.csproj" --configuration "Release" --output "publish"

      - name: Drop Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'drop'
          path: 'publish'
